use_frameworks!

platform :ios, '8.0'

target 'KPengIjkPlayer_Example' do
  pod 'KPengIjkPlayer', :path => '../'

  target 'KPengIjkPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
